### PR TITLE
fix commands in generated emails

### LINKED ISSUE #1018: Wrong links when creating a user on a local cluster
After creating a local cluster, doing a `amp -s localhost:50101 user signup`, the login contains direction on how to login, but redirects to the cloud cluster: `amp verify...` It should explicitely give the -s option. The user won't guess.

### PR DESCRIPTION
**Pull request by bquenin**
Fixes #1018 

Relying on gRPC over HTTP2 specification (https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) to determine the server address used by the client.

## How to test
```
ampmake clean build
alias amp='amp -s localhost'
amp cluster create --tag=local
amp user signup --user user
[Make sure you received an email with a valid command line for verification]
[After verification]
amp password reset user
[Make sure you received an email with a valid command line for password reset]
```

### CODE REVIEW

File: api/rpc/account/account.go [hunk 1]
```diff
@@ -48,6 +48,18 @@ func convertError(err error) error {
 	return grpc.Errorf(codes.Internal, err.Error())
 }
 
+func getServerAddress(ctx context.Context) string {
```
Comment (subfuzion) [inline api/rpc/account/account.go:51]: This is useful enough to consider moving as utility code under `pkg/grpc`. 👍

**Review by subfuzion — APPROVED** [review]
Very nice! 👍

File: api/rpc/account/account.go (hunk 1 above)
Comment (bquenin) [reply api/rpc/account/account.go:51]: Sure, I'll sneak a grpc helper in on my next API PR :)
