### PR TITLE
fix panic

### LINKED ISSUE #563: Should not get a panic for supplying invalid options
Our tools should not panic when supplied an invalid command or option. Currently, however, invalid options for `amp` do. For example, the following (mispelled) option causes a panic.

    $ amp service create --helpp

The CLI should simply display "Unrecognized option: helpp" and exit (1).

### PR DESCRIPTION
**Pull request by generalhenry**
closes: https://github.com/appcelerator/amp/issues/563

To test:
`make install`
`amp service create --helpp`

### CODE REVIEW

File: cmd/amp/main.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func main() {
 		cli.Exit(1)
 	}
 	if err := cmd.Execute(); err != nil {
-		if AMP.Verbose() == false {
+		if verbose {
```
Comment (subfuzion) [inline cmd/amp/main.go:99]: `== false` ?  How did that happen? :p

**Comment by subfuzion** [comment]
Thanks @generalhenry 👍
