### PR TITLE
Fix make test

### LINKED ISSUE #524: Integration tests are failing on master branch
Integration tests are failing because of missing binary in the test image.
CLI tests are also failing for some reason.

Here is an excerpt of the build travis build https://travis-ci.org/appcelerator/amp/builds/181707477 :
```
ok  	github.com/appcelerator/amp/tests/integration/data/influx	0.015s
ok  	github.com/appcelerator/amp/tests/integration/data/storage/etcd	1.137s
# github.com/appcelerator/amp/vendor/github.com/docker/docker/pkg/term
exec: "gcc": executable file not found in $PATH
# github.com/appcelerator/amp/vendor/github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/system
exec: "gcc": executable file not found in $PATH
FAIL	github.com/appcelerator/amp/tests/integration/rpc [build failed]
make: *** [test-integration-host] Error 2
Makefile:200: recipe for target 'test-integration-host' failed
--- FAIL: TestCmds (10.45s)
	cli_test.go:65: -----------------------------------------------------------------------------------------
	cli_test.go:67: Running spec: samples/logs.yml
	cli_test.go:67: Running spec: samples/service.yml
	cli_test.go:67: Running spec: samples/stack.yml
	cli_test.go:67: Running spec: samples/stats.yml
	cli_test.go:120: Running: amp service create appcelerator/pinger --name pingerABHmUnLUtm -p www:55915:3000
	cli_test.go:120: Running: docker service ls
	cli_test.go:120: Running: curl localhost:55915/ping
	cli_test.go:133: Mismatched expected output:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
		                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 55915: Connection refused
		 : Error: exit status 7
	cli_test.go:120: Running: amp stack up stack1yZouCyQgUP -f ../../api/rpc/stack/test_samples/sample-01.yml
	cli_test.go:120: Running: amp logs
	cli_test.go:120: Running: amp stats --container
	cli_test.go:120: Running: amp stack ls
	cli_test.go:120: Running: amp stack stop stack1yZouCyQgUP
	cli_test.go:120: Running: amp logs -m
	cli_test.go:120: Running: amp stats --cpu
	cli_test.go:133: Mismatched expected output: Error during: amp stats, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:154: Mismatched expected output: Error during: amp stats, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:155: 
	cli_test.go:120: Running: amp logs -n 10
	cli_test.go:120: Running: amp stack ls
	cli_test.go:133: Mismatched expected output: Error during: amp ls, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:154: Mismatched expected output: Error during: amp ls, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:155: 
	cli_test.go:120: Running: curl localhost:55915/ping
	context.go:22: Deadline exceeded: amp stats
	context.go:22: Deadline exceeded: amp stack ls
	context.go:22: Deadline exceeded: amp logs
	context.go:22: Deadline exceeded: amp service rm
	cli_test.go:120: Running: amp service rm pingerABHmUnLUtm
	cli_test.go:120: Running: docker service ls
	cli_test.go:120: Running: amp logs --stack stack1
	cli_test.go:71: -----------------------------------------------------------------------------------------
	cli_test.go:72: Finished!
FAIL
FAIL	github.com/appcelerator/amp/tests/cli	10.453s
make: *** [test-cli] Error 1
The command "make test" exited with 2.
Done. Your build exited with 1.
```

### PR DESCRIPTION
**Pull request by JosephGJ**
Fix #524 

related: #525 , #524 

Integration tests failing on master, removed the `dockerfile.test` so integration tests use the same Dockerfile used to build image.

Edits to the CLI tests, makes the logs less chatty and makes timeouts more forgiving.

to test
```
amp pf stop
make install
./shrink.sh local
amp pf start --local
make test
```

However, this does not fix the issue of some travis builds failing due to transport closing (amplifier crashing). 

You can see evidence of this in the travis build of this PR. 
 - https://travis-ci.org/appcelerator/amp/builds/182110005
```
--- FAIL: TestCmds (11.62s)
	cli_test.go:144: Mismatched expected output: Error during: amp stats, reason: rpc error: code = 13 desc = transport is closing
		: Error: exit status 1
	cli_test.go:144: Mismatched expected output: Error during: amp start, reason: rpc error: code = 13 desc = transport is closing
		: Error: exit status 1
	cli_test.go:141: This command : [curl localhost:51383/ping] has re-run 7 times.
FAIL
FAIL	github.com/appcelerator/amp/tests/cli	11.627s
```

Discussion on the issue: #524

### CODE REVIEW

File: tests/cli/cli_test.go [hunk 1]
```diff
@@ -110,27 +104,24 @@ func runTestSpec(t *testing.T, test *TestSpec) {
...
+				t.Fatal("Executing templating failed: %s. Error: %v", cmdSpec.Expectation, tmplErr)
 			}
 
 			// check if the command output matches the RegEx
 			expectedOutput := regexp.MustCompile(regexTmplOutput)
 			if !expectedOutput.MatchString(string(cmdOutput)) {
-				err = fmt.Errorf("Mismatched expected output: %s : Error: %v", cmdOutput, cmdErr)
-				t.Log(err)
+				errString := "Mismatched expected output: " + string(cmdOutput) + ": Error: " + cmdErr.Error()
+ 				err = errors.New(errString)
```
Comment (ndegory) [inline tests/cli/cli_test.go]: white space spotted :) (your editor probably have a Go formatting plugin for that)

**Comment by bquenin** [comment]
@JosephGJ You were right, after investigation, there's actually an issue with amplifier. I created an issue for this.
Thanks for your help!

**Review by bquenin — APPROVED** [review]
LGTM
