### PR TITLE
amplifier connects to its dependencies in parallel

### LINKED ISSUE #552: amplifier should initialize API services in parallel
`amplifier` currently initializes each API service / backend connection sequentially, starting with `etcd`. These can be done in parallel, failing if any are not available and continuing once all are connected.

### PR DESCRIPTION
**Pull request by bquenin**
Fix #552 

## Verification
    $ amp pf stop
    $ make install
    $ ./shrink local
    $ amp pf start --local
    $ make test

Also, try this:

    $ amp logs amplifier
    amplifier (server version: v0.4.0-dev, build: unknown)
    2016/12/14 16:14:09 connecting to Docker API at unix:///var/run/docker.sock version API: 1.24
    2016/12/14 16:14:09 connected to Docker at unix:///var/run/docker.sock
    2016/12/14 16:14:09 connecting to etcd at http://etcd:2379
    2016/12/14 16:14:09 Connecting to NATS-Streaming at nats://nats:4222
    2016/12/14 16:14:09 connecting to InfluxDB at http://influxdb:8086
    2016/12/14 16:14:09 connected to influxDB at http://influxdb:8086
    2016/12/14 16:14:09 connecting to elasticsearch at http://elasticsearch:9200
    2016/12/14 16:14:09 connected to etcd at http://etcd:2379
    2016/12/14 16:14:09 Connected to NATS-Streaming at nats://nats:4222
    2016/12/14 16:14:09 connected to elasticsearch at http://elasticsearch:9200
    2016/12/14 16:14:09 amplifier is listening on port 50101

You should see intertwined `connecting` and `connected` logs, not sequential anymore.

### CODE REVIEW

File: api/server/server.go [hunk 1]
```diff
@@ -35,28 +35,37 @@ const (
...
+		errors <- initNats(config)
+	}()
+	go func() {
+		errors <- initInfluxDB(config)
+	}()
+	go func() {
+		errors <- initDocker(config)
+	}()
+
+	for i := 0; i < 5; i++ { // 5 is not a magic number, it corresponds to the number of concurrent go routines
```
Comment (generalhenry) [inline api/server/server.go]: Why not use a [wait group](https://golang.org/pkg/sync/#WaitGroup)? if there are any errors the go routines can simply `log.Fatalln`

Comment (bquenin) [reply api/server/server.go]: @generalhenry why not, it's a different but maybe more orthogonal approach. I'll update my code to use it.

**Review by subfuzion — APPROVED** [review]
Nice. 👍
