### PR TITLE
stack events displayed by amp CLI / aws plugin

### LINKED ISSUE #1662: JSON Unmarshal error in AWS Cluster deployment
With every creation or deletion of an AWS cluster, there is an unmarshal error returned.
`Error: json: cannot unmarshal number into Go value of type aws.StackOutputList`

However, this does output does not appear on using `--aws-sync` option.

### PR DESCRIPTION
**Pull request by ndegory**
- Fix #1662 
- stream stack events

The CLI and the aws plugin are now better integrated with a JSON output containing stack events, stack outputs and errors.
This is fully implemented in the `cluster create` command, but would need more ironing in the `cluster delete` command, which can be done in another PR.
The `cluster update` command is not working right now, so it's not possible to test it.
```
~/Development/src/github.com/appcelerator/amp(cli-logs ✗) amp cluster create --provider aws --aws-region us-west-2 --aws-stackname nde-test --aws-parameter KeyName=xxx --aws-parameter UserWorkerSize=1 --aws-sync
[user nicolas @ localhost:50101]
Tue Oct 24 21:54:40 UTC 2017    nde-test                     CREATE_IN_PROGRESS (User Initiated)
Tue Oct 24 21:55:04 UTC 2017    Vpc                          CREATE_COMPLETE
Tue Oct 24 21:57:20 UTC 2017    ManagerAutoScalingGroup      CREATE_COMPLETE
Tue Oct 24 21:58:41 UTC 2017    ManagerWaitCondition         CREATE_COMPLETE
Tue Oct 24 21:58:47 UTC 2017    UserWorkerAutoScalingGroup   CREATE_COMPLETE
Tue Oct 24 21:58:58 UTC 2017    CoreWorkerAutoScalingGroup   CREATE_COMPLETE
Tue Oct 24 21:59:29 UTC 2017    UserWaitCondition            CREATE_COMPLETE
Tue Oct 24 22:00:20 UTC 2017    CoreWaitCondition            CREATE_COMPLETE
Tue Oct 24 22:01:42 UTC 2017    ApplicationWaitCondition     CREATE_COMPLETE
Tue Oct 24 22:01:47 UTC 2017    nde-test                     CREATE_COMPLETE
-------------------------------------------------------------------------------
VPC ID                                     | vpc-41510a27
URL for cluster health dashboard           | nde-test-ManagerEx-1M0JMQ7O8K4B4-1367928177.us-west-2.elb.amazonaws.com:8080
internal endpoint for the registry service |
public facing endpoint for the cluster     | nde-test-ManagerEx-1M0JMQ7O8K4B4-1367928177.us-west-2.elb.amazonaws.com
~/Development/src/github.com/appcelerator/amp(cli-logs ✗) amp cluster destroy --provider aws --aws-region us-west-2 --aws-stackname nde-test --aws-sync
[user nicolas @ localhost:50101]
Tue Oct 24 21:55:04 UTC 2017    Vpc                          CREATE_COMPLETE
Tue Oct 24 21:57:20 UTC 2017    ManagerAutoScalingGroup      CREATE_COMPLETE
Tue Oct 24 21:58:41 UTC 2017    ManagerWaitCondition         CREATE_COMPLETE
Tue Oct 24 21:58:47 UTC 2017    UserWorkerAutoScalingGroup   CREATE_COMPLETE
Tue Oct 24 21:58:58 UTC 2017    CoreWorkerAutoScalingGroup   CREATE_COMPLETE
Tue Oct 24 21:59:29 UTC 2017    UserWaitCondition            CREATE_COMPLETE
Tue Oct 24 22:00:20 UTC 2017    CoreWaitCondition            CREATE_COMPLETE
Tue Oct 24 22:01:42 UTC 2017    ApplicationWaitCondition     CREATE_COMPLETE
Tue Oct 24 22:01:47 UTC 2017    nde-test                     CREATE_COMPLETE
Tue Oct 24 22:02:31 UTC 2017    nde-test                     DELETE_IN_PROGRESS (User Initiated)
Tue Oct 24 22:02:34 UTC 2017    ApplicationWaitCondition     DELETE_IN_PROGRESS
Tue Oct 24 22:02:36 UTC 2017    CoreWaitCondition            DELETE_IN_PROGRESS
Tue Oct 24 22:02:36 UTC 2017    UserWaitCondition            DELETE_IN_PROGRESS
Tue Oct 24 22:02:37 UTC 2017    CoreWorkerAutoScalingGroup   DELETE_IN_PROGRESS
Tue Oct 24 22:02:38 UTC 2017    UserWorkerAutoScalingGroup   DELETE_IN_PROGRESS
Tue Oct 24 22:04:28 UTC 2017    ManagerWaitCondition         DELETE_IN_PROGRESS
Tue Oct 24 22:04:29 UTC 2017    ManagerAutoScalingGroup      DELETE_IN_PROGRESS
Tue Oct 24 22:10:53 UTC 2017    Vpc                          DELETE_IN_PROGRESS
Error: ValidationError: Stack ndetest does not existstatus code: 400, request id: 3dcbc254b90811e783bf2703644f0874
Deployment failed, see error details above

Error: Deployment failed, see error details aboveError: exit status 1
```

### CODE REVIEW

File: cli/command/cluster/plugin.go [hunk 1]
```diff
@@ -227,6 +228,47 @@ type awsPlugin struct {
 	plugin
 }
 
+func decodeAwsPluginOutput(c cli.Interface, d *json.Decoder) error {
+	var po aws.PluginOutput
+	err := d.Decode(&po)
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]:
```
err := d.Decode(&po)
if err != nil {
	return err
}
```
to
```
if err := d.Decode(&po); err != nil {
	return err
}
```

File: cli/command/cluster/plugin.go [hunk 2]
```diff
@@ -227,6 +228,47 @@ type awsPlugin struct {
...
+	// if there's an event, that's the relevant information
+	if po.Event != nil {
+		e := po.Event
+		status := e.ResourceStatus
+		if e.ResourceStatusReason != "" {
+			status = fmt.Sprintf("%s (%s)", e.ResourceStatus, e.ResourceStatusReason)
+		}
+		c.Console().Printf("%-31s %-28s %s\n", e.Timestamp, e.LogicalResourceId, status)
+		if e.ResourceType == "AWS::CloudFormation::Stack" && (e.ResourceStatus == "ROLLBACK_COMPLETE" || e.ResourceStatus == "DELETE_COMPLETE") {
+			return fmt.Errorf("Deployment failed")
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]: Error strings should not be capitalized

File: cli/command/cluster/plugin.go [hunk 3]
```diff
@@ -227,6 +228,47 @@ type awsPlugin struct {
...
+		return nil
+	}
+	// last, look for an error
+	if po.Error != "" {
+		c.Console().Printf("Error: %s\n", po.Error)
+		if strings.Contains(po.Error, "Throttling: Rate exceeded") == true {
+			// we shouldn't stop
+			return nil
+		}
+		return fmt.Errorf("Deployment failed, see error details above")
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]: Error strings should not be capitalized

File: cli/command/cluster/plugin.go [hunk 4]
```diff
@@ -227,6 +228,47 @@ type awsPlugin struct {
...
+		if e.ResourceType == "AWS::CloudFormation::Stack" && (e.ResourceStatus == "ROLLBACK_COMPLETE" || e.ResourceStatus == "DELETE_COMPLETE") {
+			return fmt.Errorf("Deployment failed")
+		}
+		// the caller should loop on the reader
+		return nil
+	}
+	// next, look for an output
+	if po.Output != nil {
+		c.Console().Printf("-------------------------------------------------------------------------------\n")
+		m := po.Output
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]:
```
for _, o := range po.Output {
```

File: cli/command/cluster/plugin.go [hunk 5]
```diff
@@ -249,28 +291,25 @@ func (p *awsPlugin) Run(c cli.Interface, args []string, env map[string]string) e
 	f := func(r io.Reader, done chan bool) {
 		d := json.NewDecoder(r)
 		for {
-			var m aws.StackOutputList
-			if err := d.Decode(&m); err == io.EOF {
+			err = decodeAwsPluginOutput(c, d)
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]:
```
if err := decodeAwsPluginOutput(c, d); err == io.EOF {
```

File: cli/command/cluster/plugin.go [hunk 6]
```diff
@@ -249,28 +291,25 @@ func (p *awsPlugin) Run(c cli.Interface, args []string, env map[string]string) e
...
-				c.Console().Error(err)
+				c.Console().Error(err) // these errors need to be fixed
 				return
 			}
-			// print the decoded output
-			for _, o := range m.Output {
-				c.Console().Printf("%s: %s\n", o.Description, o.OutputValue)
-			}
 		}
+		return
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]: unnecessary `return`

File: cli/command/cluster/plugin.go [hunk 7]
```diff
@@ -249,28 +291,25 @@ func (p *awsPlugin) Run(c cli.Interface, args []string, env map[string]string) e
...
-			if err := d.Decode(&m); err == io.EOF {
+			err = decodeAwsPluginOutput(c, d)
+			if err == io.EOF {
 				done <- true
 				break
 			} else if err != nil {
-				// If there is an error here, it is because the plugin itself is not returning
-				// json for plugin errors (yet) ... so print the buffer for now
+				done <- true
+				fmt.Println(err)
```
Comment (bquenin) [inline cli/command/cluster/plugin.go]: Is this `println` required since we have `c.Console().Error(err)` 5 lines below?

File: cli/command/cluster/plugin.go [hunk 8]
```diff
@@ -249,28 +291,25 @@ func (p *awsPlugin) Run(c cli.Interface, args []string, env map[string]string) e
...
+				// so print the buffer for now
 				outscanner := bufio.NewScanner(d.Buffered())
 				for outscanner.Scan() {
 					c.Console().Println(outscanner.Text())
 				}
-
-				done <- true
-				// Still indicate that this was an error because non-JSON responses need to be fixed
-				c.Console().Error(err)
+				c.Console().Error(err) // these errors need to be fixed
```
Comment (bquenin) [inline cli/command/cluster/plugin.go:304]: What do you mean by `// these errors need to be fixed` ?

File: cluster/plugin/aws/main.go [hunk 9]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
 	svc = cf.New(sess, aws.NewConfig().WithRegion(opts.Region).WithLogLevel(aws.LogOff))
 }
 
+// used by the create function to parse the events and send meaningful information to the CLI
+func scanEvents(mode string) error {
+	var emptyReason string
+	significantEventTypes := map[string]bool{"AWS::CloudFormation::Stack": true, "AWS::EC2::VPC": true, "AWS::CloudFormation::WaitCondition": true, "AWS::AutoScaling::AutoScalingGroup": true}
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]:
```
significantEventTypes := map[string]bool{
		"AWS::CloudFormation::Stack":         true,
		"AWS::EC2::VPC":                      true,
		"AWS::CloudFormation::WaitCondition": true,
		"AWS::AutoScaling::AutoScalingGroup": true,
	}
```

File: cluster/plugin/aws/main.go [hunk 10]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
...
+	significantEventStatuses := map[string]bool{"CREATE_IN_PROGRESS": false, "CREATE_COMPLETE": true, "CREATE_FAILED": true, "ROLLBACK_IN_PROGRESS": true, "ROLLBACK_COMPLETE": true, "DELETE_IN_PROGRESS": true}
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]:
```
significantEventStatuses := map[string]bool{
		cf.StackStatusCreateInProgress:   false,
		cf.StackStatusCreateComplete:     true,
		cf.StackStatusCreateFailed:       true,
		cf.StackStatusRollbackInProgress: true,
		cf.StackStatusRollbackComplete:   true,
		cf.StackStatusDeleteInProgress:   true,
	}
```

File: cluster/plugin/aws/main.go [hunk 11]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
...
+	eventInput := &cf.DescribeStackEventsInput{
+		StackName: aws.String(opts.StackName),
+		NextToken: nil,
+	}
+	eventIds := map[string]bool{}
+	for {
+		//resp, err := svc.DescribeStackEventsWithContext(ctx, eventInput, nil)
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]: Remove comment

File: cluster/plugin/aws/main.go [hunk 12]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
...
+				// ignore it, and continue processing the events
+				time.Sleep(time.Second)
+				continue
+			}
+			return err
+		}
+		events := resp.StackEvents
+		sort.Slice(events, func(i, j int) bool { return events[i].Timestamp.Unix() < events[j].Timestamp.Unix() })
+		for _, se := range events {
+			if eventIds[*se.EventId] == true {
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]: ```if eventIds[*se.EventId] {```

File: cluster/plugin/aws/main.go [hunk 13]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
...
+			eventIds[*se.EventId] = true
+
+			// filtering: stack events and creation / deletion of a few types
+			if *se.ResourceType == "AWS::CloudFormation::Stack" ||
+				(significantEventTypes[*se.ResourceType] == true && significantEventStatuses[*se.ResourceStatus] == true) {
+				if se.ResourceStatusReason == nil {
+					// we'll have an indirection, so better secure it
+					se.ResourceStatusReason = &emptyReason
+				}
+				eventOutput := plugin.StackEvent{EventId: *se.EventId, LogicalResourceId: *se.LogicalResourceId, ResourceStatus: *se.ResourceStatus, ResourceStatusReason: *se.ResourceStatusReason, ResourceType: *se.ResourceType, Timestamp: se.Timestamp.Format(time.UnixDate)}
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]:
```
eventOutput := plugin.StackEvent{
	EventId:              *se.EventId,
	LogicalResourceId:    *se.LogicalResourceId,
	ResourceStatus:       *se.ResourceStatus,
	ResourceStatusReason: *se.ResourceStatusReason,
	ResourceType:         *se.ResourceType,
	Timestamp:            se.Timestamp.Format(time.UnixDate),
}
 ```

File: cluster/plugin/aws/main.go [hunk 14]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
...
+				j, err := plugin.PluginOutputToJSON(&eventOutput, nil, nil)
+				if err != nil {
+					return err
+				}
+				fmt.Println(j)
+			}
+			// check end condition, based on the action
+			switch mode {
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]:
```
// check end condition, based on the action
if *se.ResourceType != "AWS::CloudFormation::Stack" {
	continue
}
switch mode {
case STACK_MODE_CREATE:
	switch *se.ResourceStatus {
	case cf.StackStatusCreateComplete, cf.StackStatusDeleteComplete, cf.StackStatusRollbackComplete:
		return nil
	default:
		// TODO: what if we don't get any of the expected statuses?
	}
case STACK_MODE_DELETE:
	switch *se.ResourceStatus {
	case cf.StackStatusDeleteFailed, cf.StackStatusDeleteComplete:
		return nil
	default:
		// TODO: what if we don't get any of the expected statuses?
	}
case STACK_MODE_UPDATE:
	switch *se.ResourceStatus {
	case cf.ResourceStatusUpdateFailed, cf.ResourceStatusUpdateComplete, cf.StackStatusRollbackComplete:
		return nil
	default:
		// TODO: what if we don't get any of the expected statuses?
	}
default:
	return fmt.Errorf("unknown mode: %s", mode)
}
```

File: cluster/plugin/aws/main.go [hunk 15]
```diff
@@ -37,27 +46,109 @@ func initClient(cmd *cobra.Command, args []string) {
...
+			fmt.Println(j)
+			os.Exit(1)
 		}
-		// use the info command to print json cluster info to stdout
 		info(cmd, args)
 	} else {
-		// only print to stdout if not sync; otherwise stdout is used to display json stack output information now
-		log.Printf("stack created: %s\n", opts.StackName)
-		log.Println(awsutil.StringValue(resp.StackId))
+		event := plugin.StackEvent{EventId: "NoSync-000", LogicalResourceId: opts.StackName, ResourceType: "AWS::CloudFormation:Stack", ResourceStatus: "CREATE_IN_PROGRESS", ResourceStatusReason: "The sync flag was not used, please check the status of the stack on the AWS console and read the output", Timestamp: time.Now().Format(time.UnixDate), StackId: *resp.StackId}
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]:
```
event := plugin.StackEvent{
	EventId:              "NoSync-000",
	LogicalResourceId:    opts.StackName,
	ResourceType:         "AWS::CloudFormation:Stack",
	ResourceStatus:       "CREATE_IN_PROGRESS",
	ResourceStatusReason: "The sync flag was not used, please check the status of the stack on the AWS console and read the output",
	Timestamp:            time.Now().Format(time.UnixDate),
	StackId:              *resp.StackId,
}
```

File: cluster/plugin/aws/main.go [hunk 16]
```diff
@@ -68,16 +159,25 @@ func update(cmd *cobra.Command, args []string) {
...
+			if jerr != nil {
+				log.Println(jerr.Error())
+				log.Fatal(err)
+			}
+			fmt.Println(j)
+			os.Exit(1)
+		}
+		info(cmd, args)
+	} else {
+		event := plugin.StackEvent{EventId: "NoSync-000", LogicalResourceId: opts.StackName, ResourceType: "AWS::CloudFormation:Stack", ResourceStatus: "UPDATE_IN_PROGRESS", ResourceStatusReason: "The sync flag was not used, please check the status of the stack on the AWS console and read the output", Timestamp: time.Now().Format(time.UnixDate), StackId: *resp.StackId}
```
Comment (bquenin) [inline cluster/plugin/aws/main.go]:
```
event := plugin.StackEvent{
	EventId:              "NoSync-000",
	LogicalResourceId:    opts.StackName,
	ResourceType:         "AWS::CloudFormation:Stack",
	ResourceStatus:       "UPDATE_IN_PROGRESS",
	ResourceStatusReason: "The sync flag was not used, please check the status of the stack on the AWS console and read the output",
	Timestamp:            time.Now().Format(time.UnixDate),
	StackId:              *resp.StackId,
}
```

File: cluster/plugin/aws/plugin/plugin.go [hunk 17]
```diff
@@ -163,13 +176,25 @@ func DeleteStack(ctx context.Context, svc *cf.CloudFormation, opts *RequestOptio
...
+	reg, err := regexp.Compile("[^a-zA-Z0-9:;,. ]+")
+	if err != nil {
+		return "", err
+	}
+
+	po := PluginOutput{
 		Output: so,
+		Event:  ev,
+	}
+	//if ev != nil && ev.LogicalResourceId != "" {
```
Comment (bquenin) [inline cluster/plugin/aws/plugin/plugin.go]: Remove comments

**Review by bquenin — CHANGES_REQUESTED** [review]
The feature is working. Needs refactoring.

File: cli/command/cluster/plugin.go (hunk 8 above)
Comment (ndegory) [reply cli/command/cluster/plugin.go:304]: it means that when this case happens (it shouldn't anymore, but in case we trap it again), it should be fixed at the plugin level.

**Review by bquenin — APPROVED** [review]
