### PR TITLE
Delete AMP stack on cluster creation failure

### LINKED ISSUE #1632: On cluster creation a failure should leave a clean state
The deployment of the AMP cluster with the ampagent shouldn't fail and leave whatever has been deployed. A rollback should be done.
In case of a creation (AMP was not running), it should delete the amp stack.
In case of an update (the amp stack already exists), it shouldn't delete the stack, _instead it should also revert to the previous state_. That last part can be done in a second step, but the rest of the issue should be addressed asap.

### PR DESCRIPTION
**Pull request by neha-viswanathan**
fixes #1632 

Handles Interrupt signals in the amp agent during cluster creation and ensures the AMP stack is deleted whenever it fails.

#### To Test

1. Hit `Ctrl+C` during `amp cluster create`. In another terminal window, run `docker service ls` command. You will see that no AMP services are running.
2. When using the dev version of the CLI, remove one image from the local cache (appcelerator/ampbeat:0.15.0-dev for instance) and run `amp cluster create`. It should fail and rollback the deployment.

### CODE REVIEW

File: cli/command/cluster/plugin.go [hunk 1]
```diff
@@ -95,7 +95,7 @@ func killContainer(c cli.Interface, name string, sig string) error {
 func RunContainer(c cli.Interface, img string, dockerOpts docker, args []string, env map[string]string, f func(r io.Reader)) error {
 	containerName := fmt.Sprintf("amp-cluster-plugin-%s", stringid.GenerateNonCryptoID())
 	dockerArgs := []string{
-		"run", "-t", "--rm", "--name", containerName,
```
Comment (ndegory) [inline cli/command/cluster/plugin.go]: why not deleting implicitly the container? Unless you make sure that you remove the container in all cases it's successfully exiting or is killed, you don't want to leave the container in a stopped state.

File: cluster/agent/cmd/install.go [hunk 2]
```diff
@@ -96,14 +109,15 @@ func install(cmd *cobra.Command, args []string) error {
 			log.Println(f)
       
 			err := deployTest(dockerCli, f, "test", 60 /* timeout in seconds */)
-			stack.Remove(dockerCli, stack.RemoveOptions{Namespaces: []string{"test"}})
+			stack.Remove(dockerCli, stack.RemoveOptions{Namespaces: []string{namespace, TEST_NAMESPACE}})
```
Comment (ndegory) [inline cluster/agent/cmd/install.go]: I don't think you want to remove the amp stack every time you remove the test stack.

File: cluster/plugin/local/plugin.go [hunk 3]
```diff
@@ -179,8 +179,8 @@ func RunAgent(ctx context.Context, c *client.Client, action string, opts *Reques
 		if err != nil {
 			fmt.Printf("%v\n", err)
 		}
-		_ = removeAgent(ctx, c, r.ID)
-		done <- true
+		//_ = removeAgent(ctx, c, r.ID)
```
Comment (ndegory) [inline cluster/plugin/local/plugin.go]: ditto, why not removing the agent container?

**Review by ndegory — CHANGES_REQUESTED** [review]

**Review by ndegory — APPROVED** [review]
